### ISSUE TITLE
Presence of WsConfigurerAdapter with a dependency to ObservationRegistry prevents ObservationRegistry's post processing and bricks tracing

### ISSUE THREAD

**Issue by N4zroth** [spring-projects/spring-ws#1435] opened 2024-10-15 18:41 UTC
Hi,
as said in the title if I have a Configuration that extends WsConfigurerAdapter with a direct or transitive dependency to ObservationRegistry,  ObservationRegistryPostProcessor.postProcessAfterInitialization is never called with ObservationRegistry as argument, thus bricking tracing for the whole project. I'm not sure what's the cause, my best guess is that some initialization order gets messed up.
You can see a small sample project here https://github.com/N4zroth/ws-tracing , both tests should work but only one is green. This seems similar to https://github.com/spring-projects/spring-security/issues/15658 but isn't fixed even with Spring Boot 3.3.4 and spring-ws 6.1.13.

**Comment by corneil** [comment] 2024-11-04 12:25
@N4zroth Can you test with Spring Framework 6.3.3 to see if the problem is resolved?

**Comment by N4zroth** [comment] 2024-11-04 16:44
@corneil just updated the project with newest spring boot dependency and it still fails.

**Comment by N4zroth** [comment] 2024-11-06 17:43
@corneil sure - we have an indirect dependency, we need a feign client that
we initialize ourselves with feign-micrometer (for authorization purposes).
The example with a simple dependency was just simpler to do :)

**Comment by corneil** [comment] 2024-11-07 10:04
If you move the bean configuration of feign client to a different configuration class you should not encounter this problem.

**Comment by N4zroth** [comment] 2024-11-07 11:06
The configuration of the Feign Bean is already a different Configuration class. This class only has a dependency on the generated Feign Bean.

**Comment by N4zroth** [comment] 2024-11-07 11:16
I updated the example with an example including Feign

**Comment by corneil** [comment] 2024-11-07 15:24
By injecting the FeignClient into the WsConfig you have the same condition. Forcing the ObservationRegistry to be created before the Web Server is causing the problem.

You can make a change so that `WsConfig` implements `ApplicationListener<ContextRefreshedEvent>` and add a method like:

```java
@Override
    public void onApplicationEvent(ContextRefreshedEvent event) {
        configureFeignClient(event.getApplicationContext().getBean(FeignClientExample.class));
    }
```    

Assuming that `configureFeignClient` will do what is required using the provided parameter.

**Comment by N4zroth** [comment] 2024-11-07 15:39
But why is this the case? Shouldn't it be possible to do it 'the normal way'? It looks similar to https://github.com/spring-projects/spring-security/issues/15658 which was fixed some time ago.

**Comment by corneil** [comment] 2024-11-08 08:56
If `ObservationRegistry` is created before the web container we have a problem. 
Even if you use an `ObjectProvider` to delay creation, when you use the object in `WsConfig` before the Web container is initialized then it doesn't properly initialize the `ObservationRegistry`.

The best is to hook it in after the context is refreshed. Then you can also deal with dynamic changes in configuration like when using Spring Cloud Config.

**Comment by hpoettker** [comment] 2024-11-13 10:24
Isn't this bug a consequence of #1425 and #1391?

The `WsConfigurerAdapter` and its sub-classes are not eligible to be postprocessed by all bean post-processors like the `ObservationRegistryPostProcessor`.

Resolving #1425 should also fix this issue, if I understand correctly.

**Closed** 2024-12-17 14:52 UTC
Labels: status: waiting-for-triage, type: bug
