### ISSUE TITLE
Changed behavior for PayloadDiffMatcher

### ISSUE THREAD

**Issue by RazorNd** [spring-projects/spring-ws#1203] opened 2021-05-31 15:39 UTC
You changed the behavior for PayloadDiffMatcher by removing the static initialization block from DiffMatcher. Whitespaces are no longer ignored when checking a payload. [Changes in current commit](https://github.com/spring-projects/spring-ws/commit/2254b0f789104a9e3614718c5289eadf9f1841da?branch=2254b0f789104a9e3614718c5289eadf9f1841da&diff=split#r51535522)

**Comment by ondrejlerch** [comment] 2021-07-13 11:42
I suggest to put back `static { XMLUnit.setIgnoreWhitespace(true); }` to `DiffMatcher` to avoid broken build investigation during `spring-ws` update as in my case. At least, it should be clearly documented in migration notes in case this is a feature and not a bug.

**Comment by gregturn** [comment] 2023-01-13 17:11
Possible duplicate of #1193.

**Comment by mathieu-amblard** [comment] 2023-02-06 08:54
Hello,

I have the same issue after migrating from Spring Boot 2.7.7 (Spring WS 3.1.4) to Spring Boot 2.7.8 (Spring WS 3.1.5).

Here is my test setup :
```java
import org.custommonkey.xmlunit.XMLUnit;
import static org.springframework.ws.test.client.RequestMatchers.payload;

@SpringBootTest(...)
class MyTest {

    static {
        XMLUnit.setIgnoreWhitespace(true);
    }

    @Test
    void test() {
        MockWebServiceServer mockWSServer = MockWebServiceServer.createServer(...);
        Source expectedRequestPayload = new ResourceSource(new ClassPathResource("request.xml"));
        Source responsePayload = new ResourceSource(new ClassPathResource("response.xml"));
        mockWSServer.expect(payload(expectedRequestPayload)).andRespond(withPayload(responsePayload));
        // ...
    }
}
```

`org.springframework.ws.test.client.RequestMatchers.payload;` uses `org.custommonkey.xmlunit.Diff;` with Spring WS `3.1.4` behind the scene whereas it uses `org.xmlunit.diff.Diff;` (xmlunit 2) with Spring WS `3.1.5`.

I do not find any equivalent to `XMLUnit.setIgnoreWhitespace(true);` for xmlunit 2.

Do you please have any suggestions ?

Thank you in advance

**Comment by marconak-itera** [comment] 2023-02-06 11:57
We are using `WhitespaceStrippedSource`

```
        var searchRequestContent = new WhitespaceStrippedSource(new StringSource(
                Files.readString(searchRequest.getFile().toPath(), StandardCharsets.UTF_8)
        ));
```

**Comment by mathieu-amblard** [comment] 2023-02-06 12:45
@marconak-itera Works like a charm 👍 !
Thank you very much.

**Comment by bgK** [comment] 2023-02-08 08:52
@gregturn, the new XmlUnit 2 implementation of `PayloadDiffMatcher` does not ignore whitespaces whereas the new implementation of `SoapEnvelopeDiffMatcher` does. It seems to me `PayloadDiffMatcher` should be fixed to ignore whitespaces to restore the initial behavior:
```diff
diff --git a/spring-ws-test/src/main/java/org/springframework/ws/test/support/matcher/xmlunit2/PayloadDiffMatcher.java b/spring-ws-test/src/main/java/org/springframework/ws/test/support/matcher/xmlunit2/PayloadDiffMatcher.java
index 45721351..bb276fff 100644
--- a/spring-ws-test/src/main/java/org/springframework/ws/test/support/matcher/xmlunit2/PayloadDiffMatcher.java
+++ b/spring-ws-test/src/main/java/org/springframework/ws/test/support/matcher/xmlunit2/PayloadDiffMatcher.java
@@ -59,6 +59,7 @@ public class PayloadDiffMatcher extends DiffMatcher {
                Document expectedDocument = createDocumentFromSource(expected);
                Document actualDocument = createDocumentFromSource(payload);
                return DiffBuilder.compare(expectedDocument) //
+                               .ignoreWhitespace() //
                                .withTest(actualDocument) //
                                .checkForSimilar() //
                                .build();
```

**Comment by RazorNd** [comment] 2023-02-08 12:12
@gregturn sorry for the long answer. I check version 3.1.5, but behavior for `PayloadDiffMatcher` in this version is still different from what it was in version 3.0.10.RELEASE.

**Comment by gregturn** [comment] 2023-04-18 14:31
Can you provide a detailed test case illustrating the issue? That would help pinpoint the issue.

**Comment by RazorNd** [comment] 2023-04-23 12:21
Test case that illustrating this issue:

Endpoint
```java
package ru.razornd.ws;

import org.springframework.ws.server.endpoint.annotation.Endpoint;
import org.springframework.ws.server.endpoint.annotation.PayloadRoot;
import org.springframework.ws.server.endpoint.annotation.ResponsePayload;
import org.springframework.xml.transform.StringSource;

import javax.xml.transform.Source;

@Endpoint
public class TestEndpoint {
    @PayloadRoot(localPart = "Request")
    @ResponsePayload
    public Source example() {
        return new StringSource("""
                <response>
                  <success>true</success>
                </response>
                """);
    }
}
```

Test class
```java
package ru.razornd.ws;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.webservices.server.WebServiceServerTest;
import org.springframework.ws.test.server.MockWebServiceClient;
import org.springframework.xml.transform.StringSource;

import static org.springframework.ws.test.server.RequestCreators.withPayload;
import static org.springframework.ws.test.server.ResponseMatchers.payload;

@WebServiceServerTest(endpoints = TestEndpoint.class)
class TestEndpointTest {

    @Autowired
    MockWebServiceClient client;

    @Test
    void example() {
        client.sendRequest(withPayload(new StringSource("<Request><Example>42</Example></Request>")))
                .andExpect(payload(new StringSource("<response><success>true</success></response>")));

    }
}
```

if you run this test against version 3.0.10.RELEASE spring-ws-test it will succeed. But if you raise the version (for example, to 3.1.1), then an error will begin to appear that the messages are different.

```
Messages are different, org.custommonkey.xmlunit.Diff
[different] Expected number of child nodes '1' but was '3' - comparing <response...> at /response[1] to <response...> at /response[1]

Payload: <response>
  <success>true</success>
</response>
org.springframework.ws.test.support.SourceAssertionError: Messages are different, org.custommonkey.xmlunit.Diff
[different] Expected number of child nodes '1' but was '3' - comparing <response...> at /response[1] to <response...> at /response[1]

Payload: <response>
  <success>true</success>
</response>
```

That is, in other words, before version 3.1.1 you ignored spaces, and after that you started to take them into account when comparing messages.

**Closed** 2023-07-14 19:35 UTC
Labels: status: waiting-for-feedback

**Comment by gregturn** [comment] 2023-07-14 19:37
Merged to `main`.

**Comment by gregturn** [comment] 2023-07-14 19:43
Backported to `3.1.x`
